spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/mcq
        driverClassName: org.postgresql.Driver
        username: dmitriy
        password: 12345
    jpa:
        show-sql: true
        properties:
            hibernate:
               format-sql: true