spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/mcq_dev
        driverClassName: org.postgresql.Driver
        username: dmitriy
        password: 12345
    jpa:
        show-sql: false
        properties:
            hibernate:
                format-sql: true
                hbm2ddl:
                    auto: update